import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hostGrotesk = localFont({
  src: "../Fonts/HostGrotesk-VariableFont_wght.ttf",
  variable: "--font-host-grotesk",
  display: "swap",
});

const nationalPark = localFont({
  src: "../Fonts/NationalPark-VariableVF.ttf",
  variable: "--font-national-park",
  display: "swap",
});

const pecita = localFont({
  src: "../Fonts/Pecita.otf",
  variable: "--font-pecita",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hostGrotesk.variable} ${nationalPark.variable} ${pecita.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
